version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: pipeline_script/ports
      timeout: 300
      runas: root
    - location: pipeline_script/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: pipeline_script/start_server
      timeout: 300
      runas: root