version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu
hooks:
  ApplicationStart:
    - location: pipeline_script/ApplicationStart.sh
      runas: ubuntu
  ApplicationStop:
    - location: pipeline_script/ApplicationStop.sh
      runas: ubuntu