version: '3.3'
services:

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_test
    env_file:
      - ./env/pgadmin.env
    ports:
      - 5050:80

  backend:
    container_name: backend_test
    build: ./backend/
    ports:
      - 81:80
    restart: unless-stopped

volumes:
  postgres:
