version: '3.3'
services:

  pgadmin:
    image: dpage/pgadmin4
    container_name: esamefinale_pgadmin
    ports:
      - 5050:80
    env_file:
      - ./env/pgadmin.env
    
  backend:
    container_name: esamefinale_BE
    build: ./backend/
    ports:
      - 80:80
    restart: unless-stopped

volumes:
  postgres:
