version: '3.3'
services:

  database:
    image: postgres:latest
    container_name: database_test
    env_file:
      - ./env/database.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_test
    env_file:
      - ./env/pgadmin.env
    ports:
      - 5050:80

  backend:
    container_name: backend_test
    build: ./backend/
    ports:
      - 81:80
    restart: unless-stopped

volumes:
  postgres:
